using System.ComponentModel;

namespace FileBotPP.Metadata
{
    public interface IMediaInfo
    {
        string GeneralUniqueId { get; set; }
        string GeneralCompleteName { get; set; }
        string GeneralComment { get; set; }
        string GeneralFormat { get; set; }
        string GeneralFormatVersion { get; set; }
        string GeneralFileSize { get; set; }
        string GeneralDuration { get; set; }
        string GeneralOverallBitRate { get; set; }
        string GeneralOverallBitRateMode { get; set; }
        string GeneralEncodedDate { get; set; }
        string GeneralWritingApplication { get; set; }
        string GeneralWritingLibrary { get; set; }
        string GeneralFormatInfo { get; set; }
        string GeneralFormatProfile { get; set; }
        string GeneralCodecId { get; set; }
        string GeneralTaggedDate { get; set; }
        string VideoId { get; set; }
        string VideoFormat { get; set; }
        string VideoStandard { get; set; }
        string VideoFormatInfo { get; set; }
        string VideoFormatProfile { get; set; }
        string VideoFormatVersion { get; set; }
        string VideoFormatSettingsBvop { get; set; }
        string VideoFormatSettingsQpel { get; set; }
        string VideoFormatSettingsGmc { get; set; }
        string VideoFormatSettingsMatrix { get; set; }
        string VideoFormatSettingsCabac { get; set; }
        string VideoFormatSettingsReFrames { get; set; }
        string VideoFormatSettingsGop { get; set; }
        string VideoMuxingMode { get; set; }
        string VideoCodecId { get; set; }
        string VideoCodecIdHint { get; set; }
        string VideoCodecIdInfo { get; set; }
        string VideoDuration { get; set; }
        string VideoSourceDuration { get; set; }
        string VideoBitRate { get; set; }
        string VideoWidth { get; set; }
        string VideoHeight { get; set; }
        string VideoDisplayAspectRatio { get; set; }
        string VideoFrameRateMode { get; set; }
        string VideoFrameRate { get; set; }
        string VideoColorSpace { get; set; }
        string VideoChromaSubSampling { get; set; }
        string VideoBitDepth { get; set; }
        string VideoCompressionMode { get; set; }
        string VideoScanType { get; set; }
        string VideoBitsPixelFrame { get; set; }
        string VideoStreamSize { get; set; }
        string VideoTimeCodeOfFirstFrame { get; set; }
        string VideoCodeSource { get; set; }
        string VideoWritingLibrary { get; set; }
        string VideoEncodingSettings { get; set; }
        string VideoLanguage { get; set; }
        string VideoDefault { get; set; }
        string VideoForced { get; set; }
        string VideoColorRange { get; set; }
        string VideoMatrixCoefficients { get; set; }
        string VideoGopOpenClosed { get; set; }
        string VideoGopOpenClosedOfFirstFrame { get; set; }
        string VideoMaximumBitRate { get; set; }
        string VideoNominalBitRate { get; set; }
        string VideoEncodedDate { get; set; }
        string VideoTaggedDate { get; set; }
        string VideoFormatSettingsPictureStructure { get; set; }
        string VideoBitRateMode { get; set; }
        string VideoScanOrder { get; set; }
        string AudioId { get; set; }
        string AudioFormat { get; set; }
        string AudioFormatVersion { get; set; }
        string AudioFormatInfo { get; set; }
        string AudioFormatProfile { get; set; }
        string AudioMode { get; set; }
        string AudioModeExtension { get; set; }
        string AudioFormatSettingEndianness { get; set; }
        string AudioNominalBitRate { get; set; }
        string AudioMinimumBitRate { get; set; }
        string AudioCodecId { get; set; }
        string AudioCodecIdHint { get; set; }
        string AudioDuration { get; set; }
        string AudioSourceDuration { get; set; }
        string AudioBitRateMode { get; set; }
        string AudioBitRate { get; set; }
        string AudioChannel { get; set; }
        string AudioChannelPositions { get; set; }
        string AudioSamplingRate { get; set; }
        string AudioCompressionMode { get; set; }
        string AudioStreamSize { get; set; }
        string AudioDefault { get; set; }
        string AudioForced { get; set; }
        string AudioLanguage { get; set; }
        string AudioAlignment { get; set; }
        string AudioInterleaveDuration { get; set; }
        string AudioInterleavePreloadDuration { get; set; }
        string AudioWritingLibrary { get; set; }
        string AudioEncodingSettings { get; set; }
        string AudioDelayRelativeToVideo { get; set; }
        string AudioMaximumBitRate { get; set; }
        string AudioEncodedDate { get; set; }
        string AudioTaggedDate { get; set; }
        string TextId { get; set; }
        string TextFormat { get; set; }
        string TextCodecId { get; set; }
        string TextCodecIdInfo { get; set; }
        string TextTitle { get; set; }
        string TextLanguage { get; set; }
        string TextDefault { get; set; }
        string TextForced { get; set; }
        event PropertyChangedEventHandler PropertyChanged;
    }
}